### ISSUE TITLE
Give url to GPT

### ISSUE THREAD

**Issue by katakahas** [katakahas/paper_summary_bot#1]
Give (arxiv) url retrieved by the bot with prompt to GPT and return response.
You can rewrite /src/gpt_read.py (rename this file is ok)

**Comment by KU-onji** [comment]
#14 でたぶん全部完了？

**Comment by katakahas** [comment]
大体終わったっぽいのでissue閉じます。ありがとうございました。
(それはそれとして、ファインチューニングとかやりたいという人がいたらやってもらってもよいです)
